### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by epessina** [epessina/LandslideMonitor#1]
- [ ] Create an on-screen tutorial.

- [ ] Fix the insertion date of the local landslides after synchronization. Right now, when the user synchronizes his local landslides with the server, the `createdAt` and `updatedAt` values in the main database are set to the time of the synchronization instead of the actual values saved in the local database.

- [ ] Add a textual explanation of the landslides type in the insert screen.

- [ ] Write a GDPR.

- [ ] Rearrange the translation file.
